name: benchmark

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - "main"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Clean docker
        run: |
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true

      - name: Install requirements
        run: pip install -r dev-requirements.txt

      - name: Run benchmark
        run: python run.py

      - name: Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./results

  readme:
    name: Update Results
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -r render/requirements.txt
      - run: python render.py
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Commit changes
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "📝 Update results"
          git tag ${{ steps.date.outputs.date }}
          git push -f --tags
          git push
